'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Category
    Public Property CategoryID As Integer
    Public Property Name As String
    Public Property ModifiedDate As Nullable(Of Date)

    Public Overridable Property SubCategories As ICollection(Of SubCategory) = New HashSet(Of SubCategory)

End Class
