'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property ProductID As Integer
    Public Property SubcategoryID As Nullable(Of Integer)
    Public Property CatalogNumber As String
    Public Property Name As String
    Public Property Cost As Nullable(Of Decimal)
    Public Property Price As Nullable(Of Decimal)
    Public Property ModifiedDate As Nullable(Of Date)

    Public Overridable Property SubCategory As SubCategory

End Class
