'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SubCategory
    Public Property SubCategoryID As Integer
    Public Property CategoryID As Nullable(Of Integer)
    Public Property Name As String
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ManufacturedBY As String

    Public Overridable Property Category As Category
    Public Overridable Property Products As ICollection(Of Product) = New HashSet(Of Product)

End Class
